### ISSUE TITLE
pip installation doesn't install pygments library

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/open-project-linter#24]
@fhocutt just giving this a test run, and `pip install --pre open-project-linter` works great but doesn't seem to install the `pygments` requirement. (Even though I see it right there in [requirements.txt](https://github.com/OpenNewsLabs/open-project-linter/blob/master/requirements.txt).)

I was testing on a fresh Python3 virtual environment, and manually running `pip install pygments` fixed the issue. Relevant console feedback below:

```
(linter)
$ pip install --pre open-project-linter
Collecting open-project-linter
  Downloading open_project_linter-0.3dev-py3-none-any.whl
Collecting gitpython (from open-project-linter)
  Downloading GitPython-2.1.1-py2.py3-none-any.whl (441kB)
    100% |████████████████████████████████| 450kB 2.5MB/s
Collecting pyyaml (from open-project-linter)
  Using cached PyYAML-3.12.tar.gz
Collecting gitdb2>=2.0.0 (from gitpython->open-project-linter)
  Downloading gitdb2-2.0.0-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 7.3MB/s
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython->open-project-linter)
  Downloading smmap2-2.0.1-py2.py3-none-any.whl
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /Users/ryanp/Library/Caches/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
Successfully built pyyaml
Installing collected packages: smmap2, gitdb2, gitpython, pyyaml, open-project-linter
Successfully installed gitdb2-2.0.0 gitpython-2.1.1 open-project-linter-0.3.dev0 pyyaml-3.12 smmap2-2.0.1

$ openlinter --help
Traceback (most recent call last):
  File "/Users/ryanp/.virtualenvs/linter/bin/openlinter", line 7, in <module>
    from openlinter.openlinter import main
  File "/Users/ryanp/.virtualenvs/linter/lib/python3.5/site-packages/openlinter/openlinter.py", line 16, in <module>
    import openlinter.rules as rules
  File "/Users/ryanp/.virtualenvs/linter/lib/python3.5/site-packages/openlinter/rules.py", line 48, in <module>
    import pygments.lexers as lexers
ImportError: No module named 'pygments'
```

**Comment by fhocutt** [comment]
Fixed in https://github.com/OpenNewsLabs/open-project-linter/commit/2cd439a7b5e788b2d9ad4c14f0e4af9fe7c247df .
