### ISSUE TITLE
pip install missing a default rules.yml?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNewsLabs/open-project-linter#25]
@fhocutt this was a bit confusing to me -- in my fresh virtualenv with a fresh pip installation (via `$ pip install --pre open-project-linter`), I was trying to run `openlinter -d .` to test my current working directory. Console output:

```
$ openlinter -d .
Traceback (most recent call last):
  File "/Users/ryanp/.virtualenvs/linter/bin/openlinter", line 11, in <module>
    sys.exit(main())
  File "/Users/ryanp/.virtualenvs/linter/lib/python3.5/site-packages/openlinter/openlinter.py", line 35, in main
    with open(args.rules, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ryanp/Code/projects/opennews/openlinter/rules.yml'
```

I looked at `openlinter --help` and see where I can pass in a `rules.yml` file (which seems like a cool way to be able to customize the linter, for sure), but in reading the documentation I didn't see anything to suggest I'd need to create that file before I could run the linter.

I figured I could at least try pointing to the `rules.yml` from the linter itself, but it looks like the `pip install` doesn't include that file. Or at least as I burrowed into my `site-packages` dir in the virtualenv, I wasn't finding it in the `openlinter` package.

Seems like providing a default file and pointing to that location might be the smoothest experience for users?

**Comment by ryanpitts** [comment]
FWIW, I copied a quick `rules.yml` into my working dir and the linter ran great!

**Comment by fhocutt** [comment]
Fixed in https://github.com/OpenNewsLabs/open-project-linter/commit/02e3421792f23b15c6f9e98cf0d66d14c0630553 .

**Comment by ryanpitts** [comment]
yoooooo looks good!

```
$ pip install --pre open-project-linter
Collecting open-project-linter
  Downloading open_project_linter-0.4dev-py3-none-any.whl
Collecting pygments (from open-project-linter)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting gitpython (from open-project-linter)
  Using cached GitPython-2.1.1-py2.py3-none-any.whl
Collecting pyyaml (from open-project-linter)
Collecting gitdb2>=2.0.0 (from gitpython->open-project-linter)
  Using cached gitdb2-2.0.0-py2.py3-none-any.whl
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython->open-project-linter)
  Using cached smmap2-2.0.1-py2.py3-none-any.whl
Installing collected packages: pygments, smmap2, gitdb2, gitpython, pyyaml, open-project-linter
Successfully installed gitdb2-2.0.0 gitpython-2.1.1 open-project-linter-0.4.dev0 pygments-2.2.0 pyyaml-3.12 smmap2-2.0.1

$ openlinter --help
usage: openlinter [-h] [-d DIRECTORY] [-r RULES] [-v]

optional arguments:
  -h, --help            show this help message and exit
  -d DIRECTORY, --directory DIRECTORY
                        The local path to your repository's base directory.
                        Defaults to the current working directory.
  -r RULES, --rules RULES
                        The path to the rules configuration file, a YAML file
                        containing the rules you would like to check for.
                        Defaults to current-working-
                        directory/openlinter/rules.yml.
  -v, --version         show program's version number and exit

$ openlinter -d .
  LICENSE exists and has content
  README exists and has content
! CONTRIBUTING not found in .
  code files detected
  version control using git
  multiple git branches found
! no development branch found
  multiple commits on a branch found
```

**Comment by fhocutt** [comment]
Sweet!
